"use client";

import { useState } from "react";
import { ChevronDown } from "lucide-react";
import { GitHubIcon } from "../icons";
import { Section } from "./Section";
import projectsData from "@/content/projects.json";

type Project = {
  name: string;
  url: string;
  featured: boolean;
  tagline: string;
  problem: string;
  architecture: string;
  features: string[];
  tradeoffs: string[];
  demonstrates: string;
  complexity: string;
  languages: string[];
  frameworks: string[];
};

const projects = (projectsData as { projects: Project[] }).projects;

function Chips({ items }: { items: string[] }) {
  const seen = new Set<string>();
  const unique = items.filter((s) => {
    const k = s.toLowerCase();
    if (seen.has(k)) return false;
    seen.add(k);
    return true;
  });
  if (!unique.length) return null;
  return (
    <div className="flex flex-wrap gap-1.5">
      {unique.map((s) => (
        <span
          key={s}
          className="rounded-full border border-veil px-2.5 py-0.5 font-mono text-[11px] text-mist"
        >
          {s}
        </span>
      ))}
    </div>
  );
}

function FeaturedCard({ p }: { p: Project }) {
  const [open, setOpen] = useState(false);
  return (
    <article className="rounded-2xl border border-veil bg-curtain p-6 transition-colors hover:border-gold/40">
      <div className="flex items-start justify-between gap-4">
        <a
          href={p.url}
          target="_blank"
          rel="noreferrer"
          className="group inline-flex items-center gap-2"
        >
          <h3 className="font-display text-xl text-ivory group-hover:text-gold transition-colors">
            {p.name}
          </h3>
          <GitHubIcon className="h-4 w-4 text-mist group-hover:text-gold transition-colors" />
        </a>
        {p.complexity ? (
          <span className="shrink-0 font-mono text-[11px] uppercase tracking-wider text-gold/80">
            {p.complexity}
          </span>
        ) : null}
      </div>

      <p className="mt-2 text-[15px] leading-relaxed text-ivory/85">{p.tagline}</p>
      <div className="mt-4">
        <Chips items={[...p.languages, ...p.frameworks].slice(0, 8)} />
      </div>

      <button
        onClick={() => setOpen(!open)}
        aria-expanded={open}
        className="mt-4 inline-flex items-center gap-1.5 text-sm text-gold hover:underline underline-offset-4"
      >
        {open ? "Less" : "Architecture & honest tradeoffs"}
        <ChevronDown className={`h-4 w-4 transition-transform ${open ? "rotate-180" : ""}`} />
      </button>

      {open ? (
        <div className="mt-4 space-y-4 border-t border-veil pt-4 text-sm leading-relaxed">
          {p.architecture ? (
            <div>
              <div className="font-mono text-[11px] uppercase tracking-wider text-mist mb-1">
                Architecture
              </div>
              <p className="text-ivory/80">{p.architecture}</p>
            </div>
          ) : null}
          {p.tradeoffs.length ? (
            <div>
              <div className="font-mono text-[11px] uppercase tracking-wider text-mist mb-1">
                Tradeoffs — auto-extracted from the code, kept honest
              </div>
              <ul className="list-disc pl-5 space-y-1 text-mist">
                {p.tradeoffs.map((t) => (
                  <li key={t.slice(0, 32)}>{t}</li>
                ))}
              </ul>
            </div>
          ) : null}
          {p.demonstrates ? (
            <p className="text-gold/90 italic">{p.demonstrates}</p>
          ) : null}
        </div>
      ) : null}
    </article>
  );
}

export function Projects() {
  const featured = projects.filter((p) => p.featured);
  const others = projects.filter((p) => !p.featured);

  return (
    <Section id="projects" eyebrow="Projects" title="Public work, honestly summarized">
      <p className="max-w-prose text-mist -mt-4 mb-10 text-[15px] leading-relaxed">
        Every card below is auto-generated by the same pipeline that feeds her AI
        rep: it reads each repo&apos;s actual source and writes a structured summary —
        including the tradeoffs. Ask the chat about any of them.
      </p>

      <div className="grid gap-5 md:grid-cols-2">
        {featured.map((p) => (
          <FeaturedCard key={p.name} p={p} />
        ))}
      </div>

      {others.length ? (
        <div className="mt-10">
          <h3 className="font-mono text-xs tracking-[0.22em] uppercase text-mist">
            Also on GitHub
          </h3>
          <div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            {others.map((p) => (
              <a
                key={p.name}
                href={p.url}
                target="_blank"
                rel="noreferrer"
                className="rounded-xl border border-veil px-4 py-3 transition-colors hover:border-gold/40"
              >
                <div className="text-sm text-ivory">{p.name}</div>
                <div className="mt-1 text-xs text-mist line-clamp-2">{p.tagline}</div>
              </a>
            ))}
          </div>
        </div>
      ) : null}
    </Section>
  );
}
